import type { PortfolioProject, PortalProject, TechnicalLibraryEntry } from "@/types/domain";

export const demoPortfolio: PortfolioProject[] = [
  {
    id: "1",
    slug: "elite-business-park-facade-riyadh",
    titleAr: "واجهة مجمع النخبة للأعمال - الرياض",
    titleEn: "Elite Business Park Facade - Riyadh",
    category: "Commercial",
    summaryAr: "تنفيذ واجهات ألمنيوم وزجاج عالية الأداء لمجمع أعمال متعدد المباني مع متطلبات عزل حراري وصوتي دقيقة.",
    summaryEn: "Execution of high-performance aluminum and glass facades for a multi-building business park with strict thermal and acoustic targets.",
    location: "Riyadh",
    completionYear: 2025,
    featured: true,
    images: [
      { url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab", altAr: "واجهة مبنى أعمال", altEn: "Business facade" },
      { url: "https://images.unsplash.com/photo-1460574283810-2aab119d8511", altAr: "تفاصيل المعالجة المعمارية", altEn: "Architectural detail" },
    ],
  },
  {
    id: "2",
    slug: "logistics-hub-steel-gates-dammam",
    titleAr: "بوابات المجمع اللوجستي - الدمام",
    titleEn: "Logistics Hub Steel Gates - Dammam",
    category: "Industrial",
    summaryAr: "تصنيع وتركيب بوابات حديدية ثقيلة وأنظمة حماية محيطية لمجمع لوجستي يعمل بنظام تشغيل عالي الكثافة.",
    summaryEn: "Fabrication and installation of heavy-duty steel gates and perimeter protection systems for a high-throughput logistics hub.",
    location: "Dammam",
    completionYear: 2024,
    featured: true,
    images: [
      { url: "https://images.unsplash.com/photo-1504307651254-35680f356dfd", altAr: "حالة البوابة قبل التطوير", altEn: "Before gate condition", isBefore: true },
      { url: "https://images.unsplash.com/photo-1513828583688-c52646db42da", altAr: "حالة البوابة بعد التنفيذ", altEn: "After gate completion", isAfter: true },
    ],
  },
  {
    id: "3",
    slug: "private-villa-thermal-systems-jeddah",
    titleAr: "فيلا خاصة بأنظمة حرارية - جدة",
    titleEn: "Private Villa Thermal Systems - Jeddah",
    category: "Residential",
    summaryAr: "توريد وتركيب نوافذ وأبواب ألمنيوم حرارية بزجاج مزدوج مع تفاصيل تنفيذ تحافظ على الهوية المعمارية للمشروع.",
    summaryEn: "Supply and installation of thermal aluminum windows and doors with double glazing while preserving the project’s architectural identity.",
    location: "Jeddah",
    completionYear: 2026,
    featured: true,
    images: [
      { url: "https://images.unsplash.com/photo-1523217582562-09d0def993a6", altAr: "تفاصيل باب ألمنيوم", altEn: "Aluminum door detail" },
      { url: "https://images.unsplash.com/photo-1494526585095-c41746248156", altAr: "واجهة سكنية", altEn: "Residential facade" },
    ],
  },
];

export const demoTechnicalLibrary: TechnicalLibraryEntry[] = [
  {
    id: "1",
    entryType: "profiles",
    slug: "uf-90-thermal-hi",
    titleAr: "UF-90 نظام حراري عالي العزل",
    titleEn: "UF-90 High Insulation Thermal System",
    summaryAr: "نظام واجهات ونوافذ للمشاريع التي تتطلب كفاءة طاقة أعلى ومقاومة مناخية قوية.",
    summaryEn: "Facade and window system for projects requiring elevated energy efficiency and weather resistance.",
    specs: {
      Depth: "90 mm",
      Glazing: "28-52 mm",
      "Air Tightness": "Class 4",
      "Water Tightness": "E1200",
    },
  },
  {
    id: "2",
    entryType: "glass",
    slug: "triple-silver-low-e-laminated",
    titleAr: "زجاج Low-E ثلاثي الفضة مع طبقة أمان",
    titleEn: "Triple Silver Low-E Laminated Glass",
    summaryAr: "خيار متقدم لتقليل الكسب الحراري الشمسي ورفع الأمان الصوتي والإنشائي.",
    summaryEn: "Advanced option to reduce solar heat gain and improve acoustic and safety performance.",
    specs: {
      Thickness: "8+16+8 mm",
      "U-Value": "1.2 W/m²K",
      SHGC: "0.28",
      Acoustic: "40 dB",
    },
  },
  {
    id: "3",
    entryType: "finishes",
    slug: "marine-grade-powder-coat",
    titleAr: "دهان بودرة بدرجة حماية بحرية",
    titleEn: "Marine Grade Powder Coating",
    summaryAr: "تشطيب معدني مخصص للبيئات الرطبة والساحلية مع مقاومة تآكل طويلة الأمد.",
    summaryEn: "Metal finish engineered for humid and coastal environments with long-term corrosion resistance.",
    specs: {
      Coating: "80-100 µm",
      Standard: "Qualicoat Seaside",
      "Salt Spray": "1500h",
    },
  },
];

export const demoPortalProjects: PortalProject[] = [
  {
    id: "PRJ-26011",
    name: "Elite Business Park - Phase A",
    clientName: "Elite Developments",
    city: "Riyadh",
    progress: 72,
    status: "Production Running",
    expectedCompletion: "2026-08-12",
    stages: [
      {
        key: "documentation",
        titleAr: "التوثيق",
        titleEn: "Documentation",
        status: "completed",
        progressPercent: 100,
        notes: "Contract and approved shop drawings archived.",
        updatedAt: "2026-04-02",
      },
      {
        key: "procurement",
        titleAr: "التوريد",
        titleEn: "Procurement",
        status: "completed",
        progressPercent: 100,
        notes: "Main profiles, glass packages, and accessories received.",
        updatedAt: "2026-04-24",
      },
      {
        key: "production",
        titleAr: "الإنتاج",
        titleEn: "Production",
        status: "in_progress",
        progressPercent: 72,
        notes: "Fabrication and assembly in progress.",
        updatedAt: "2026-05-06",
      },
      {
        key: "logistics",
        titleAr: "اللوجستيات",
        titleEn: "Logistics",
        status: "pending",
        progressPercent: 0,
        notes: "Pending production release.",
        updatedAt: "2026-05-06",
      },
      {
        key: "handover",
        titleAr: "التسليم",
        titleEn: "Handover",
        status: "pending",
        progressPercent: 0,
        notes: "Not started.",
        updatedAt: "2026-05-06",
      },
    ],
  },
  {
    id: "PRJ-26019",
    name: "Private Villa - Al Basateen",
    clientName: "Private Client",
    city: "Jeddah",
    progress: 41,
    status: "Procurement",
    expectedCompletion: "2026-09-18",
    stages: [
      {
        key: "documentation",
        titleAr: "التوثيق",
        titleEn: "Documentation",
        status: "completed",
        progressPercent: 100,
        notes: "Design package and final quotation approved.",
        updatedAt: "2026-04-18",
      },
      {
        key: "procurement",
        titleAr: "التوريد",
        titleEn: "Procurement",
        status: "in_progress",
        progressPercent: 41,
        notes: "Special glass shipment in transit.",
        updatedAt: "2026-05-08",
      },
      {
        key: "production",
        titleAr: "الإنتاج",
        titleEn: "Production",
        status: "pending",
        progressPercent: 0,
        notes: "Starts after full material clearance.",
        updatedAt: "2026-05-08",
      },
      {
        key: "logistics",
        titleAr: "اللوجستيات",
        titleEn: "Logistics",
        status: "pending",
        progressPercent: 0,
        notes: "Not started.",
        updatedAt: "2026-05-08",
      },
      {
        key: "handover",
        titleAr: "التسليم",
        titleEn: "Handover",
        status: "pending",
        progressPercent: 0,
        notes: "Not started.",
        updatedAt: "2026-05-08",
      },
    ],
  },
];
